### PR TITLE
Fixes Weasel Dependencies in Wolverine.RDBMS

### LINKED ISSUE #637: Incompatible JasperFX.Core version in WolverineFx.Postgresql
**Describe the bug**
This error is thrown while calling `host.SetupResources();`

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Weasel.Postgresql.PostgresqlProvider' threw an exception.
 ---> System.IO.FileNotFoundException: Could not load file or assembly 'JasperFx.Core, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.
File name: 'JasperFx.Core, Version=1.4.0.0, Culture=neutral, PublicKeyToken=null'
   at Weasel.Core.DatabaseProvider`6..ctor(String defaultDatabaseSchemaName)
   at Weasel.Postgresql.PostgresqlProvider..ctor()
   at Weasel.Postgresql.PostgresqlProvider..cctor()
   --- End of inner exception stack trace ---
   at Weasel.Postgresql.PostgresqlMigrator..ctor()
   at Wolverine.Postgresql.PostgresqlMessageStore..ctor(DatabaseSettings databaseSettings, DurabilitySettings settings, ILogger`1 logger)
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   --- End of inner exception stack trace ---
   at System.Reflection.MethodBaseInvoker.InvokeDirectByRefWithFewArgs(Object obj, Span`1 copyOfArgs, BindingFlags invokeAttr)
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture)
   at System.Activator.CreateInstance(Type type, Object[] args)
   at Lamar.IoC.Instances.ConstructorInstance.quickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.QuickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.<>c__DisplayClass27_0.<quickResolve>b__0(CtorArg x)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at Lamar.IoC.Instances.ConstructorInstance.quickResolve(Scope scope)
   at Lamar.IoC.Instances.ConstructorInstance.QuickResolve(Scope scope)
   at Lamar.IoC.Frames.InjectedServiceField.ToVariableExpression(LambdaDefinition definition)
   at JasperFx.CodeGeneration.Expressions.LambdaDefinition.ExpressionFor(Variable variable)
   at System.Linq.Enumerable.SelectArrayIterator`2.Fill(ReadOnlySpan`1 source, Span`1 destination, Func`2 func)
   at System.Linq.Enumerable.SelectArrayIterator`2.ToArray()
   at System.Dynamic.Utils.CollectionExtensions.ToReadOnly[T](IEnumerable`1 enumerable)
   at System.Linq.Expressions.Expression.NewArrayInit(Type type, IEnumerable`1 initializers)
   at Lamar.IoC.Frames.ListAssignmentFrame`1.WriteExpressions(LambdaDefinition definition)
   at Lamar.IoC.Instances.FuncResolverDefinition.BuildResolver()
   at Lamar.IoC.Instances.GeneratedInstance.BuildFuncResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.buildResolver(Scope scope)
   at Lamar.IoC.Instances.GeneratedInstance.ToResolver(Scope topScope)
   at Lamar.ServiceGraph.FindResolver(Type serviceType)
   at Lamar.IoC.Scope.GetInstance(Type serviceType)
   at Lamar.Container.Microsoft.Extensions.DependencyInjection.ISupportRequiredService.GetRequiredService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Oakton.Resources.ResourcesCommand.FindResources(IServiceProvider services, String typeName, String resourceName)
   at Oakton.Resources.ResourceHostExtensions.SetupResources(IHost host, CancellationToken cancellation, String resourceType, String resourceName)
```

I believe this is due to an incompatible version of `Weasel.Postgresql` which depends on `Weasel.Core` that expects an older version of `JasperFX`

**To Reproduce**
1. Create a new project with postgresql persistance
2. Call `host.SetupResources()`

**Desktop (please complete the following information):**
 - OS: Windows 11 23H2 22631.2715
 - Version WolverineFx.Postgresql 1.12.0

### PR DESCRIPTION
**Pull request by redbaty**
This updates Weasel dependencies, and uses PostgresqlObjectName/SqlServerObjectName instead of the generic DbObjectName in the SqlServerMessageStore/PostgresqlMessageStore

### CODE REVIEW

**Comment by redbaty** [comment]
This fixes #637

**Comment by redbaty** [comment]
Already fixed by f934de86462b7dc8982392f47accb1a7838ce4b9

**Comment by jeremydmiller** [comment]
Crap, I didn't see this before I did a hackier, quicker fix. I will get this rebased later and deal with the conflicts and pull this in. I do think I want to wait until Marten / Weasel are up though.

THANK YOU!

**Comment by jeremydmiller** [comment]
@redbaty Your PR is still helpful, I "fixed" it cruder than you did.

**Comment by jeremydmiller** [comment]
We ended up changing Weasel to make this unnecessary.

**Pull request closed without merging**
